/* Conformité C3 — données FICTIVES pour les tests (aucun texte de la vraie trousse : le dépôt est public). */
import { emptyPlatformIdentity, type PlatformIdentity } from "@/lib/plateforme/identite";
import type { Installer } from "../../types";

/** Trousse fictive : même structure que la vraie (section 2, parties, préambule, articles 2.n, signatures, annexes A à E). */
export const FICTIVE_TROUSSE = [
  "TROUSSE FICTIVE DE TEST",
  "VERSION DE TRAVAIL 9.9",
  "1 janvier 2030",
  "## 1  Avant-propos fictif",
  "Texte fictif sans importance.",
  "## 2  Entente fictive de test",
  "PROJET FICTIF",
  "### Entre les parties",
  "[RAISON SOCIALE DE LA PLATEFORME], société fictive, au [ADRESSE], NEQ [NEQ], représentée par [NOM ET TITRE].",
  "ET",
  "[RAISON SOCIALE DE L’INSTALLATEUR], [forme juridique], au [ADRESSE], NEQ [NEQ], licence RBQ [NUMÉRO ET SOUS-CATÉGORIES], représentée par [NOM ET TITRE].",
  "Ensemble, les parties fictives.",
  "### Préambule",
  "Premier considérant fictif.",
  "Second considérant fictif.",
  "### 2.1  Objet fictif",
  "Alinéa fictif un, voir l’article 2.3 et l’annexe C.",
  "Alinéa fictif deux.",
  "### 2.2  Avis fictifs",
  "Avis fictif au [COURRIEL JURIDIQUE DE LA PLATEFORME], tribunal fictif de [DISTRICT].",
  "### 2.3  Fin fictive",
  "Préavis fictif de trente jours, selon l’annexe B.",
  "Défaut fictif corrigé en dix jours.",
  "### Signatures",
  "Pour la société fictive",
  "Pour le partenaire fictif",
  "Nom  [NOM]Titre  [TITRE]Signature  ______Date  ______",
  "Nom  [NOM]Titre  [TITRE]Signature  ______Date  ______",
  "Note fictive sur la preuve.",
  "## Annexe A  Fiche fictive",
  "Champ",
  "Valeur",
  "Identifiant",
  "[ID UNIQUE]",
  "Montant",
  "[MONTANT] $",
  "### Formule",
  "Commission fictive = [prix fictif].",
  "## Annexe B  Dossier fictif",
  "Document",
  "Exigence",
  "Contrôle",
  "Assurance",
  "Montant fictif",
  "Certificat",
  "Automobile",
  "Montant fictif auto",
  "Certificat annuel",
  "## Annexe C  Liste fictive",
  "☐  Premier point fictif du chantier.",
  "☐  Deuxième point fictif du chantier.",
  "☐  Troisième point fictif du chantier.",
  "## Annexe D  Renseignements fictifs",
  "Élément",
  "Règle",
  "Objet",
  "Règle fictive un.",
  "Conservation",
  "Règle fictive deux.",
  "## Annexe E  Niveaux fictifs",
  "Mesure",
  "Or",
  "Standard",
  "Probation",
  "Réponse",
  "Même jour",
  "Un jour",
  "Plus",
  "Paragraphe fictif final sur les seuils.",
  "## 3  Autre section fictive",
  "### 3.1  Rien",
  "Texte fictif.",
].join("\n");

export const PLATFORM: PlatformIdentity = {
  ...emptyPlatformIdentity(),
  legalName: "Entreprise Exemple inc.",
  legalForm: "Société par actions",
  neq: "1234567890",
  address: "1, rue Exemple, Laval (Québec) H0H 0H0",
  phone: "514 555-0100",
  emailLegal: "juridique@exemple.ca",
  emailService: "service@exemple.ca",
  emailPrivacy: "vieprivee@exemple.ca",
  privacyOfficer: { name: "Alex Exemple", title: "Président", email: "vieprivee@exemple.ca", phone: "" },
  representative: { name: "Alex Exemple", title: "Président" },
};

export function installer(id: string, company: string, createdAt: Date): Installer {
  return { id, company, contactName: "Julie Exemple", phone: "514 555-0142", email: `${id}@exemple.ca`, rbq: "", basePostalCode: "H7N 1A1", base: null, radiusKm: 60, extraRegions: [], brands: [], systemTypes: [], active: true, maxOpenJobs: null, notes: "", createdAt: createdAt.toISOString(), updatedAt: createdAt.toISOString() };
}

/** Environnement de test : dossier temporaire, aucun envoi réel (hors production, les envois sont simulés). */
export const testEnv = (dir: string, by: string) => ({ GESTION_DATA_DIR: dir, TEXTOS_DATA_DIR: dir, LEAD_JOURNAL_DIR: `${dir}/leads`, ADMIN_EMAILS: by, NODE_ENV: "test" as const, TEXTOS_ENVOIS_DEV: "", TWILIO_ACCOUNT_SID: "", TWILIO_AUTH_TOKEN: "", TWILIO_PHONE_NUMBER: "", GEMINI_API_KEY: "" });
